datasets:
    mesh_folder:
        data_folder: 'transfer_data/meshes/straps_output'
deformation_transfer_path: 'transfer_data/smpl2smplx_deftrafo_setup.pkl'
mask_ids_fname: 'transfer_data/smplx_mask_ids.npy'
summary_steps: 100

edge_fitting:
    per_part: False

optim:
#    type: 'trust-ncg'
    type: 'lbfgs'
    maxiters: 5
    gtol: 1e-06
    ftol: 1e-4
    lr: 5

body_model:
    model_type: "smplx"
    gender: "neutral"
    folder: "transfer_data/body_models"
    use_compressed: False
    use_face_contour: True
    smplx:
        betas:
            num: 10
        expression:
            num: 10
